[package]
name = "collatz_bigint_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
num-bigint = "0.4.4"
num-traits = "0.2"
regex="1.9.5"